# Generated by Django 4.2.7 on 2025-03-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='paymentdocument',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentdocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='PaymentDocument',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
