# Generated by Django 4.2.7 on 2025-03-27 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_delete_invoice'),
        ('accounts', '0007_propertyownersubscription_payment_amount_and_more'),
        ('payments', '0006_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('rent', 'Rent'), ('security_deposit', 'Security Deposit'), ('maintenance', 'Maintenance Fee'), ('late_fee', 'Late Fee')], default='rent', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stripe_checkout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_invoices', to='properties.bankaccount')),
                ('lease_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_invoices', to='properties.leaseagreement')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_invoices', to='properties.property')),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_invoices', to='properties.propertyunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_invoices', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
