# Generated by Django 4.2.7 on 2025-03-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
