# Generated by Django 4.2.7 on 2025-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('security_deposit', 'Security Deposit'), ('maintenance', 'Maintenance Fee'), ('late_fee', 'Late Fee'), ('subscription', 'Subscription')], max_length=20),
        ),
    ]
