# Generated by Django 4.2.7 on 2025-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('security_deposit', 'Security Deposit'), ('maintenance', 'Maintenance Fee')], default='rent', max_length=20),
        ),
    ]
