# Generated by Django 5.2 on 2025-04-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_alter_invoice_payment_type"),
        ("properties", "0025_alter_leaseagreement_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="lease_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.leaseagreement",
            ),
        ),
    ]
