# Generated by Django 5.2 on 2025-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_alter_payment_lease_agreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="due_date",
            field=models.DateField(blank=True),
        ),
    ]
