# Generated by Django 5.2 on 2025-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_alter_payment_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
