# Generated by Django 5.2 on 2025-04-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_alter_payment_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
