# Generated by Django 5.2 on 2025-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_method_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
