# Generated by Django 4.2.7 on 2025-04-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_propertyownersubscription_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration_months',
            field=models.PositiveIntegerField(default=1, help_text='Duration in months'),
        ),
    ]
