# Generated by Django 4.2.7 on 2025-04-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscription_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_tenant',
            field=models.IntegerField(default=1),
        ),
    ]
