# Generated by Django 4.2.7 on 2025-04-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subscription_max_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='max_tenant',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='max_units',
            field=models.IntegerField(default=1),
        ),
    ]
