# Generated by Django 4.2.7 on 2025-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_subscription_max_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyownersubscription',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
