# Generated by Django 4.2.7 on 2025-04-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_propertyownersubscription_stripe_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyownersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
