# Generated by Django 4.2.7 on 2025-04-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_propertyownersubscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('property_owner', 'Property Owner'), ('tenant', 'Tenant'), ('property_manager', 'Property Manager')], max_length=20),
        ),
    ]
