# Generated by Django 4.2.7 on 2025-04-04 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_propertymaintenance_property_unit'),
        ('accounts', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_properties', models.ManyToManyField(related_name='property_managers', to='properties.property')),
                ('maintenance_requests', models.ManyToManyField(related_name='assigned_managers', to='properties.propertymaintenance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Manager',
                'verbose_name_plural': 'Property Managers',
                'ordering': ['-created_at'],
            },
        ),
    ]
