# Generated by Django 4.2.7 on 2025-04-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_propertymanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyManager',
        ),
    ]
