# Generated by Django 5.2 on 2025-04-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_delete_propertymanager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
