# Generated by Django 4.2.7 on 2025-03-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('terminated', 'Terminated'), ('expired', 'Expired')], max_length=20),
        ),
    ]
