# Generated by Django 4.2.7 on 2025-03-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_leaseagreement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('unit_type', models.CharField(choices=[('STUDIO', 'Studio'), ('1BHK', '1 Bedroom'), ('2BHK', '2 Bedrooms'), ('3BHK', '3 Bedrooms')], max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('square_feet', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='property',
            name='monthly_rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_feet',
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Property_unit',
        ),
        migrations.AddField(
            model_name='propertyunit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property'),
        ),
    ]
