# Generated by Django 4.2.7 on 2025-03-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyunit_remove_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyunit',
            name='unit_type',
        ),
    ]
