# Generated by Django 4.2.7 on 2025-03-25 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_propertyunit_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('Paypal', 'Paypal'), ('Stripe', 'Stripe')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('account_mode', models.CharField(choices=[('Sandbox', 'Sandbox'), ('Live', 'Live')], default='Sandbox', max_length=20)),
                ('client_id', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
