# Generated by Django 4.2.7 on 2025-03-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_leaseagreement_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
