# Generated by Django 4.2.7 on 2025-03-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='property_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyunit'),
        ),
    ]
