# Generated by Django 4.2.7 on 2025-03-26 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscription_stripe_price_id'),
        ('properties', '0009_leaseagreement_property_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tenants', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_properties', to='accounts.tenant')),
            ],
            options={
                'verbose_name_plural': 'Tenant Properties',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'property')},
            },
        ),
    ]
