# Generated by Django 4.2.7 on 2025-03-26 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_tenantproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='rent_due_day',
            field=models.PositiveIntegerField(default=1, help_text='Day of the month when rent is due (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
