# Generated by Django 4.2.7 on 2025-03-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_leaseagreement_rent_due_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='property_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_agreements', to='properties.propertyunit'),
        ),
    ]
