# Generated by Django 4.2.7 on 2025-03-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscription_stripe_price_id'),
        ('properties', '0012_alter_leaseagreement_property_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('rent', 'Rent'), ('security_deposit', 'Security Deposit'), ('maintenance', 'Maintenance'), ('utility', 'Utility'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.bankaccount')),
                ('lease_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='properties.leaseagreement')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
