# Generated by Django 4.2.7 on 2025-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_invoice_payment_url_invoice_stripe_checkout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20),
        ),
    ]
