# Generated by Django 4.2.7 on 2025-03-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_property_property_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
