# Generated by Django 4.2.7 on 2025-03-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_delete_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymaintenance',
            name='property_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='properties.propertyunit'),
        ),
    ]
