# Generated by Django 4.2.7 on 2025-04-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_propertymanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunit',
            name='business_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
