# Generated by Django 4.2.7 on 2025-04-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_propertyunit_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunit',
            name='bedrooms',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
