# Generated by Django 4.2.7 on 2025-04-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_alter_propertyunit_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunit',
            name='bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propertyunit',
            name='bedrooms',
            field=models.IntegerField(),
        ),
    ]
