# Generated by Django 4.2.7 on 2025-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_propertyunit_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunit',
            name='bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propertyunit',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
    ]
