# Generated by Django 4.2.7 on 2025-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_alter_propertyunit_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunit',
            name='kitchen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
