# Generated by Django 4.2.7 on 2025-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_propertyunit_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunit',
            name='kitchen',
            field=models.PositiveIntegerField(),
        ),
    ]
