# Generated by Django 4.2.7 on 2025-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_alter_propertyunit_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
