# Generated by Django 5.2 on 2025-04-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0026_alter_bankaccount_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
    ]
