# Generated by Django 5.2 on 2025-04-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0027_alter_bankaccount_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_occupied",
            field=models.BooleanField(default=False),
        ),
    ]
