# Generated by Django 5.2 on 2025-04-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0028_property_is_occupied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyunit",
            name="kitchen",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
