# Generated by Django 5.2 on 2025-04-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0029_alter_propertyunit_kitchen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyunit",
            name="kitchen",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
